[package]
name = "tracen-generated-conformance"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracen_pack = { path = "../../.." }
tracen_ir = { path = "../../../../tracen_ir" }

[build-dependencies]
tracen_pack = { path = "../../.." }
